### ISSUE TITLE
Форма заказа

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#13]
**Календарь**
Дни, не доступные для бронирования, лучше стилизовать соответствующим образом ("задизейблить"), т.к. сейчас при клике на эти даты складывается ощущение, что календарь сломался
![1](https://user-images.githubusercontent.com/19621113/92310538-1e530680-efb8-11ea-9693-0fab8284f65d.gif)

Слишком узкое поле для кол-ва гостей:
![1](https://user-images.githubusercontent.com/19621113/92310618-d41e5500-efb8-11ea-8031-95066b448e4f.png)

**Comment by Nelliza** [comment]
С календарями сейчас происходит что-то неладное: при попытке установить дату выезда позже ноября скрипт намертво вешает страницу (
![1](https://user-images.githubusercontent.com/19621113/92775358-ff34ea00-f3a6-11ea-9875-3f7e405ae515.gif)

**Comment by Nelliza** [comment]
Также еще одна важная деталь: при попытке изменить дату прибытия выбранная дата устанавливается для поля выезда вместо поля прибытия (в случае, если она ближе к дате прибытия), и наоборот
![1](https://user-images.githubusercontent.com/19621113/92776013-88e4b780-f3a7-11ea-899e-fdd634afba1d.gif)

**Comment by fmvasilenko** [comment]
> Также еще одна важная деталь: при попытке изменить дату прибытия выбранная дата устанавливается для поля выезда вместо поля прибытия (в случае, если она ближе к дате прибытия), и наоборот
> ![1](https://user-images.githubusercontent.com/19621113/92776013-88e4b780-f3a7-11ea-899e-fdd634afba1d.gif)

А здесь просто логика работы немного другая. Оно выставляет дату ту, которая ближе к выбранной. То есть если нажать на соседний день рядом с датой выезда - то он поменяет дату выезда, если с датой въезда - то дату въезда. Мне показалось, что так удобнее с точки зрения пользователя, если он хочет сдвинуть одну из дат на соседний день и посмотреть что будет. (меньше действий для пользователя).
А нажатие на одно из полей просто открывает календарь, без привязки к дате приезда или выезда.

**Comment by fmvasilenko** [comment]
По поводу зависания - нашел в чем проблема, исправляю

**Comment by fmvasilenko** [comment]
> А здесь просто логика работы немного другая. Оно выставляет дату ту, которая ближе к выбранной. То есть если нажать на соседний день рядом с датой выезда - то он поменяет дату выезда, если с датой въезда - то дату въезда. Мне показалось, что так удобнее с точки зрения пользователя, если он хочет сдвинуть одну из дат на соседний день и посмотреть что будет. (меньше действий для пользователя).
> А нажатие на одно из полей просто открывает календарь, без привязки к дате приезда или выезда.

В задании просто ничего не было сказано про сценарии работы календаря и я сделал так, как мне казалось удобнее)

**Comment by fmvasilenko** [comment]
> Также еще одна важная деталь: при попытке изменить дату прибытия выбранная дата устанавливается для поля выезда вместо поля прибытия (в случае, если она ближе к дате прибытия), и наоборот
> ![1](https://user-images.githubusercontent.com/19621113/92776013-88e4b780-f3a7-11ea-899e-fdd634afba1d.gif)

Здесь просто логика работы такая и есть. Меняется та дата, которая ближе к выбранной. Мне показалось, что так будет удобнее для пользователя. 
То есть вряд ли он выбрал дату заезда 11 сентября, выезда - в октябре, а потом нажал на 12 сентября, желая поменять дату выезда. Скорее всего, решил проверить, что будет, если заехать 12 числа, вместо 11. И я пытался упростить ему работу и сделать интерфейс более дружелюбным)
А клик по полю с датами просто открывает календарь и ни к чему не привязан, т.к. две эти идеи вместе невозможны.

В задании ничего не было сказано про сценарии работы календаря. 
Могу, если надо, переделать)

**Comment by Nelliza** [comment]
> А клик по полю с датами просто открывает календарь и ни к чему не привязан, т.к. две эти идеи вместе невозможны.

И все-таки - при клике на конкретное поле (прибытие / выезд) юзер с очень высокой степенью вероятности ожидает манипулировать именно им ) В ином случае (по твоей логике) в макете было бы реализовано единое поле для range-календаря. Так что тут сценарий напрашивается сам собой, имхо )

**Comment by fmvasilenko** [comment]
> > А клик по полю с датами просто открывает календарь и ни к чему не привязан, т.к. две эти идеи вместе невозможны.
> 
> И все-таки - при клике на конкретное поле (прибытие / выезд) юзер с очень высокой степенью вероятности ожидает манипулировать именно им ) В ином случае (по твоей логике) в макете было бы реализовано единое поле для range-календаря. Так что тут сценарий напрашивается сам собой, имхо )

В макете есть и единое поле для выбора даты `filter-date-dropdown`, и двойное `date-dropdown`)
Плюс календарь есть отдельно от этих полей в ките. Я его делал отдельным модулем, чтобы можно было потом использовать и как выпадающий элемент в обеих ситуациях и отдельно.

В любом случае, я доработал логику. Теперь в ките и в `filter-date-dropdown` все работает как раньше, а `date-dropdown` есть возможность выбрать дату, в зависимости от поля, но:
Если нажать, например на поле с датой выезда, после этого выбрать дату, то календарь перейдет в такой же режим, как и был до этого. 
То есть если пользователь хочет поменять дату выезда, то он ее меняет, а потом, не закрывая календарь может двигать обе даты. На мой взгляд, это позволит избежать лишних действий по закрыванию одного поля и открыванию другого, для выбора второй даты.

Еще добавил hover эффекты для более интуитивного понимания происходящего.

**Comment by Nelliza** [comment]
> Если пользователь хочет поменять одну из дат - у него есть возможность сделать это интуитивно. Но дальше ему не надо закрывать календарь и открывать его еще раз для редактирования второй даты.

Да, все верно.

Давай еще немного доработаем UI: у тебя отсутствует возможность бронирования прошедших дат (что логично), но есть активная стрелка на предыдущий месяц от текущей даты, что несколько сбивает с толку

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/93813157-5cf4ec00-fc5b-11ea-8c84-c74e20af5839.png)
Кнопка "Очистить" при отсутствии значений не нужна, у тебя в поле ниже как раз верно реализовано
