### ISSUE TITLE
Мобильное меню

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#14]
Для мобильной версии следует реализовать гамбургер-меню, сейчас на мобилках выглядит не очень красиво:
![1](https://user-images.githubusercontent.com/19621113/92310774-29a73180-efba-11ea-9080-80894f3abdc9.png)

**Comment by fmvasilenko** [comment]
Я сделал гамбургер, но есть 2 но:

1. В шаблоне не было стилей для мобильной версии, так что сделал все "на глаз"
2. Чтобы избежать использования JS, вставил 
```pug
label.header__sandwich-icon(for="header-menu-toggle")
<...>
input.header__sandwich-input(id="header-menu-toggle" type="checkbox")
``` 
Таким образом на странице `headers` гамбургер во втором хедере не работает. Мне кажется, это допустимым, так как это лишь демо страница, а в продакшене хедер всегда только один на страницу.

**Comment by Nelliza** [comment]
> Я сделал гамбургер, но есть 2 но:
> 
> 1. В шаблоне не было стилей для мобильной версии, так что сделал все "на глаз"
> 2. Чтобы избежать использования JS, вставил
> 
> ```
> label.header__sandwich-icon(for="header-menu-toggle")
> <...>
> input.header__sandwich-input(id="header-menu-toggle" type="checkbox")
> ```
> 
> Таким образом на странице `headers` гамбургер во втором хедере не работает. Мне кажется, это допустимым, так как это лишь демо страница, а в продакшене хедер всегда только один на страницу.

Ок, тоже думаю, что ничего страшного

**Comment by Nelliza** [comment]
Только кнопки-ссылки в меню сейчас не работают, поправить надо )

**Comment by fmvasilenko** [comment]
Ссылки "Войти" и "Регистрация" слетели после добавления деструктуризации в модуль кнопки. Поправил.

Во все остальные ссылки в хедере и футере проставил заглушку `/mock-address/change-me`, как указано в стандартах FSD. Соответствующих страниц в макете нет.

**Comment by Nelliza** [comment]
> Ссылки "Войти" и "Регистрация" слетели после добавления деструктуризации в модуль кнопки.

Да, я видела, что слетели, именно их и имела в виду )
