### ISSUE TITLE
Деструктуризация

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#15]
![1](https://user-images.githubusercontent.com/19621113/92311101-b226d180-efbc-11ea-98d4-e153ea6e27d5.png)
Используй преимущества деструктуризации, с ней код становится чище и снижается вероятность возникновения опечаток

**Comment by fmvasilenko** [comment]
1. Меня здесь смущает, что получается много отдельных переменных:
```js
const {classes, type, href, style, disabled, value, icon} = config;
```
То есть мы, по сути, выносим большое количество переменных в глобальную область видимости.
И в других файлах их может быть значительно больше. Стоит ли все равно использовать деструктуризацию?
    
2. Стоит ли использовать деструктуризацию для вложенных объектов? Например:
```js
const {value, classes, vocabulary} = config;
const {title, icon, currencyIcon, text} = vocabulary;
```

**Comment by Nelliza** [comment]
> То есть мы, по сути, выносим большое количество переменных в глобальную область видимости.

Почему в глобальную, в область видимости миксина. В большинстве случаев да, стоит, это нагляднее и проще, можно задавать дефолтные значения и т.д.

**Comment by Nelliza** [comment]
> 1. Стоит ли использовать деструктуризацию для вложенных объектов?

Стоит, если ты уверен, что справа у тебя всегда объект (а не `undefined` или `null`, иначе поймаешь ошибку)

**Comment by Nelliza** [comment]
https://github.com/fmvasilenko/TOXIN/blob/f781939f1d50528926e654c4592a72ef8ef9abee/src/common.blocks/calendar/CalendarLogic.js#L88-L95
Здесь тоже напрашивается деструктуризация, а еще группировка по полям вместо группировки по коллбэкам
