### ISSUE TITLE
Ссылки на внешние страницы

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#16]
Согласно [нашим стандартам](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#tags--external-link), ссылки на внешние страницы должны иметь атрибуты `target="_blank"` и `rel="noopener noreferrer"`. Ссылки в футере потенциально ведут на внешние страницы, поэтому следует добавить им эти атрибуты

**Comment by fmvasilenko** [comment]
Я добавил атрибуты к ссылкам на соцсети.
Остальные ссылки, по идее, внутренние.

**Comment by Nelliza** [comment]
Ок, именно ссылки на соцсети имелись в виду )

**Comment by Nelliza** [comment]
Ок, именно ссылки на соцсети имелись в виду )
