### ISSUE TITLE
Страница подбора номера

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#17]
![1](https://user-images.githubusercontent.com/19621113/93814196-df31e000-fc5c-11ea-8394-f3dc51c7dacc.png)
В карточках номеров почему-то отсутствует стоимость, плюс переключатели у каруселей отсутствуют во всех карточках, кроме первой (при этом стрелочки есть)

**Comment by fmvasilenko** [comment]
Цена тоже слетела после деструктуризации) Поправил.

Картинок было по одной потому что в макете их было по одной предоставлено. 
Для примера продублировал картинки из других номеров.
Также убрал стрелочки и точки для случая, если загружена всего одна картинка. (пример - номер 982)
