### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#19]
https://github.com/fmvasilenko/TOXIN/blob/2bd475e6c37e9657dae1d5823ff4fbbd74a12f47/src/common.blocks/button/button.pug#L8
Переменные, которые не переопределяются, объявляй сразу с `const`; посмотри плиз везде в проекте

**Comment by Nelliza** [comment]
https://github.com/fmvasilenko/TOXIN/blob/2bd475e6c37e9657dae1d5823ff4fbbd74a12f47/src/common.blocks/checkbox-button/checkbox-button.pug#L9
Для атрибутов используй двойные кавычки

**Comment by Nelliza** [comment]
https://github.com/fmvasilenko/TOXIN/blob/c1b664abab06fdc92524380b83747cc3cf2e6e52/src/common.blocks/donut-chart/donut-chart.pug#L31
Используй строгое сравнение вместо нестрогого https://github.com/airbnb/javascript#comparison--eqeqeq

**Comment by Nelliza** [comment]
https://github.com/fmvasilenko/TOXIN/blob/8b10f57371c3982513ef362c60e2b9f8b19df6a6/src/pages/room-details/room-details.pug#L18-L19
Что будет, если понадобится передать сюда не два изображения, а одно? Или четыре? Сейчас этот код лишен гибкости, посмотри в сторону перебирающих методов массивов

**Comment by fmvasilenko** [comment]
> Что будет, если понадобится передать сюда не два изображения, а одно? Или четыре? Сейчас этот код лишен гибкости, посмотри в сторону перебирающих методов массивов

Так там же в макете больше двух изображений не предусмотрено. Одно большое и 2 маленьких.
А если передано всего одно, то вместо второго - дырка?)
Мне, если честно, не совсем был понятен такой макет, так как количество изображений строго задано и если передавать больше или меньше - непонятно что с ними делать. Отсюда и отсутствие гибкости)
![image](https://user-images.githubusercontent.com/62238648/94718261-2c4b3b80-035a-11eb-88cf-7beda799d64b.png)

**Comment by Nelliza** [comment]
Тут я хотела сделать акцент на том, что при работе с массивами нужно учитывать

> А если передано всего одно, то вместо второго - дырка?)
> Мне, если честно, не совсем был понятен такой макет, так как количество изображений строго задано и если передавать больше или меньше - непонятно что с ними делать. Отсюда и отсутствие гибкости)

При правильной реализации никаких дырок быть не должно ) Смотри:
![1](https://user-images.githubusercontent.com/19621113/95012897-fe5d4400-0644-11eb-8967-6f3cc12b721f.png)
![2](https://user-images.githubusercontent.com/19621113/95012905-074e1580-0645-11eb-80e3-33f55b6215d8.png)
Именно такую гибкость я и имела в виду. А нынешняя твоя реализация не позволяет ее обеспечить, плюс если ты передашь только одно изображение в правый блок (нижний кейс), получишь не просто дырку, а ошибку компиляции, что еще хуже )

**Comment by Nelliza** [comment]
> Для атрибутов используй двойные кавычки

Вот здесь еще осталось:
https://github.com/fmvasilenko/TOXIN/blob/26c77e3f68c61b8c20c620d677b1f76670985e8e/src/layout/landing.pug#L8-L10
https://github.com/fmvasilenko/TOXIN/blob/26c77e3f68c61b8c20c620d677b1f76670985e8e/src/layout/left-sidebar.pug#L9-L11
