### ISSUE TITLE
Линтинг кода

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#20]
Добавь плиз скрипт для линтинга в _package.json_

**Comment by Nelliza** [comment]
Сейчас линтер выдает 26 ошибок, нужно их исправить

**Comment by Nelliza** [comment]
Ты сейчас по сути закрыл линтеру рот, везде отключив правило `no-param-reassign`, так делать не нужно ) Переназначать аргументы - плохая практика, попробуй думать о них как о константах

**Comment by Nelliza** [comment]
То же самое с отключением правила `no-unused-vars` - зачем ты присваиваешь результат создания инстансов классов переменным, которые ты нигде в дальнейшем не используешь?

**Comment by Nelliza** [comment]
Правило `no-new` можно будет прописать в файле _.eslintrc_

**Comment by fmvasilenko** [comment]
> Ты сейчас по сути закрыл линтеру рот, везде отключив правило `no-param-reassign`, так делать не нужно ) Переназначать аргументы - плохая практика, попробуй думать о них как о константах

Это в основном сделано в файлах Component.js и Blocks.js. Но там это необходимо, так как таким образом происходит связывание данных. То есть линтер говорит мне не делать именно то, что я и хотел сделать. Мне было важно привязываться и менять исходный объект, а не его копию.
Изначально я эти места и не прикрывал от линтера, потому и были ошибки.

В Component.js, например, у каждого класса - наследника есть свойство state. Когда я добавляю новый модуль в раздел children - у меня автоматически происходит привязка переменных state, у которых задано свойство isGlobal к родительскому объекту, по имени, либо по псевдониму. Таким образом, если в дочернем элементе, например календаре, есть поле state.arrivalDate и в date-dropdown такое же поле, то это просто ссылки на один и тот же объект.

**Comment by fmvasilenko** [comment]
> В Component.js, например, у каждого класса - наследника есть свойство state...

На самом деле, архитектура здесь не самая удачная, но на момент, когда я ее создавал, я еще не знал про вещи вроде observer. Поэтому все, что там есть - исключительно мои "изобретения".

Мне в целом кажется интересной идея с рекурсивным спуском и привязкой отдельных переменных в дочерних объектах к родительским. Это позволяет создать необходимую связанность данных, но ограничить область видимости отдельных компонентов, а также уменьшить захламленность их state.
Сейчас я бы реализовал ее несколько по другому, но проблема в том, что все js объекты наследуются от Component.js и любые изменения ведут к изменениям во всем проекте(

**Comment by Nelliza** [comment]
Сильная связанность - это серьезный архитектурный недостаток, возможно, ты уже читал об основных проблемах этого подхода. Тут, к сожалению, придется переписывать (

**Comment by fmvasilenko** [comment]
> Сильная связанность - это серьезный архитектурный недостаток, возможно, ты уже читал об основных проблемах этого подхода. Тут, к сожалению, придется переписывать (

Я имел в виду не связанность кода, а привязку данных.
Для того, чтобы отделить модули друг от друга я в тот момент придумал штуку, похожую на observer.
Например у нас есть кнопка с лайком. У него есть переменная state вида:
```js
this.state = {
  isLiked: {
    value: false,
    isGlobal: true,
    subscribers: [],
  },
  likesNumber: {
    value: 12,
    subscribers: [],
  }
}
```
И есть комментарий пользователя, у которого в `this.children` находится `likeButton` и в котором нам по какой-то причине тоже нужно количество лайков (например для ранжирования). У него свой state:
```js
this.state = {
  likesNumber: {
    value: 12,
    subscribers: [],
  }
}
```
Так вот поскольку у кнопки лайка в переменной `likesNumber` стоит `isGlobal: true` - оба модуля начинают ссылаться на один объект `likesNumber`, что позволяет иметь в памяти всего одну переменную, связанную с количеством лайков. Оба модуля могут добавлять туда своих подписчиков. При изменении значения вызываются все подписчики. 
> isGlobal показывает, что модулю не нужно создавать свой отдельный обзервер, а взять ссылку на него у родителя и добавить туда своих подписчиков.

По сути `state` - это набор обзерверов. И мы просто пробрасываем ссылку на нужные обзерверы из `child` модуля в родительский. При этом, если нам, например, нужна эта переменная на еще более высоком уровне, то в родительском элементе также можно поставить `isGlobal: true` и ссылка пробросится еще на один уровень выше.

Мне нравится, что модуль имеет ссылки только на те обзерверы, которые ему нужны. Также, что у нас есть только одно место для хранения одной переменной.
Но из минусов я могу выделить наследование от Component.js, а также то, как реализован вызов подписчиков и присвоение значений переменным (были реализованы через геттеры, сеттеры, что добавляет непрозрачности коду)

**Comment by Nelliza** [comment]
> Я имел в виду не связанность кода, а привязку данных.

А я как раз имела в виду сильную связанность, или если точнее - сильное зацепление, т.е. у тебя один модуль жестко привязан к другому, может залезать в его внутренности и напрямую изменять их

> Таким образом, если в дочернем элементе, например календаре, есть поле state.arrivalDate и в date-dropdown такое же поле, то это просто ссылки на один и тот же объект.

Опять же, рассматривая указанный тобой пример - при малейшем изменении одного из модулей (к примеру, при переименовании того же поля `arrivalDate`) придется вносить правки и в другой, это и есть взаимозависимость

**Comment by Nelliza** [comment]
> и любые изменения ведут к изменениям во всем проекте(

Да, эти изменения предполагают немалые трудозатраты, но они точно окупятся наращиванием скиллов. В целом круто, что ты экспериментировал, изобретал свои способы взаимодействия между компонентами, и несомненно, это очень полезный опыт в плане прокачки
