### ISSUE TITLE
Gitignore

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#21]
Добавь пожалуйста папки _dist_ и _build_ в гитигнор

**Comment by fmvasilenko** [comment]
> Добавь пожалуйста папки _dist_ и _build_ в гитигнор

У меня папка dist является корнем для github pages. Если я ее удалю - то пропадут опубликованные страницы

**Comment by Nelliza** [comment]
> У меня папка dist используется для github pages. Если я ее удалю - то пропадут опубликованные страницы.

Можно воспользоваться плагином, к примеру, gh-pages, я его использовала


> А в build лежат конфиги для webpack. Их разве не стоит хранить в репозитории?

Их стоит хранить, только переименуй плиз папку _build_ в _config_, а то название вводит в заблуждение
