### ISSUE TITLE
PerfectPixel

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#22]
Страница регистрации чуть съехала
![1](https://user-images.githubusercontent.com/19621113/94336340-1e5c8a00-ffeb-11ea-8b48-9a357b740ccc.png)

**Comment by Nelliza** [comment]
То же самое со страницей входа
![2](https://user-images.githubusercontent.com/19621113/94336347-30d6c380-ffeb-11ea-96ad-f33e175e17fb.png)

**Comment by Nelliza** [comment]
Здесь галерею чуть подправь плиз
![3](https://user-images.githubusercontent.com/19621113/94336404-c5412600-ffeb-11ea-8306-194332b010e3.png)

**Comment by fmvasilenko** [comment]
> Здесь галерею чуть подправь плиз

Вот у меня, кстати, был вопрос: если картинки не совпадают с картинками в макете - это критично? 
То есть в макете есть картинки с масками и они между собой не отцентрованы, а накиданы так, как дизайнеру показалось симпатичнее. Мне нужно пытаться также подогнать или можно просто соблюсти внешние размеры, а внутри допустимы расхождения (например диван сдвинут на 10 пикселов влево)

**Comment by fmvasilenko** [comment]
Я поправил галерею, а вот с регистрацией и страницей входа - проблема. 
У меня сейчас все четко совпадает в PerfectPixel. Расхождение по высоте - 0.5px. Плюс все отступы численно равны тем, что в макете. Если я переделаю по твоей картинке - то тогда у меня будет смещение, что, по сути, не решает проблему. Плюс численно отступы будут уже не правильные.
Как лучше поступить: оставить как есть или все таки поменять отступы? Или может проблема вообще по другому решается?
P.S. Пробовал в последнем хроме и в яндекс браузере.

**Comment by Nelliza** [comment]
Скинь пожалуйста твои скрины с открытым окошком настроек расширения

**Comment by fmvasilenko** [comment]
![image](https://user-images.githubusercontent.com/62238648/94604444-60622600-02a0-11eb-8f9a-fe415a6d539a.png)
![image](https://user-images.githubusercontent.com/62238648/94604495-77087d00-02a0-11eb-9f42-c90b7afdc887.png)

На странице регистрации в макете форма сдвинута на пару пикселей, поэтому несовпадение по горизонтали.

**Comment by Nelliza** [comment]
> На странице регистрации в макете форма сдвинута на пару пикселей, поэтому несовпадение по горизонтали.
Не страшно ) Давай тогда оставим, как сейчас, я закрою ишью, а если у других ревьюеров тоже будут расхождения, всегда успеешь поправить
