### ISSUE TITLE
Постраничная навигация

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#25]
Частично у тебя уже настроена постраничная навигация, но не везде. Было бы круто, если бы при нажатии на кнопку подбора номера на главной происходил переход на страницу 
c карточками номеров (_Search room_), а при нажатии на любую из карточек - на страницу информации о номере (_Room details_). Думаю, это не строго обязательно, но желательно )

**Comment by Nelliza** [comment]
Думаю, `href` не нужно определять в конфиге. По идее, если учитывать, что в реальном проекте это были бы ссылки на разные страницы - динамическими в адресе были бы только айдишники (поле `suiteNumber` в твоем конфиге)

**Comment by fmvasilenko** [comment]
Я поменял логику: теперь ссылка у всех одна и та же: `room-details.html`, а `suiteNumber`передается в качестве GET параметра.
Можно еще сделать ссылки вида `room-details/888`, но такой URL надо парсить на стороне сервера и gh-pages, соответственно, такое не потянут)

**Comment by fmvasilenko** [comment]
И сразу тогда вопрос:
Есть ли какие-то правила именования GET параметров?
Я назвал параметр: `suite_number`. Так и оставить или лучше `suiteNumber`?

**Comment by Nelliza** [comment]
> Можно еще сделать ссылки вида `room-details/888`, но такой URL надо парсить на стороне сервера и gh-pages, соответственно, такое не потянут)

Ну это слишком для учебного проекта )

**Comment by Nelliza** [comment]
> И сразу тогда вопрос:
> Есть ли какие-то правила именования GET параметров?
> Я назвал параметр: `suite_number`. Так и оставить или лучше `suiteNumber`?

Единого стандарта нет, я бы назвала `suiteNumber` в целях единообразия, но это не принципиально )
