### ISSUE TITLE
Сильное зацепление

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#26]
Следует избавиться от сильного зацепления модулей, подробности [здесь](https://github.com/fmvasilenko/TOXIN/issues/20#issuecomment-703230642)

**Comment by Nelliza** [comment]
https://github.com/fmvasilenko/TOXIN/blob/407066e032d180d0adeb9bfa05f8c028ad3159ab/src/common.blocks/suite/SuiteLogic.js#L47-L48
Здесь посмотри плиз в сторону [свойств-аксессоров](https://learn.javascript.ru/property-accessors) - они упростят твой код и сделают его более эффективным

**Comment by fmvasilenko** [comment]
> Здесь посмотри плиз в сторону [свойств-аксессоров](https://learn.javascript.ru/property-accessors) - они упростят твой код и сделают его более эффективным

У меня изначально и были геттеры-сеттеры)
А тут я подумал, что есть некая непрозрачность, если делать `this.state.imageDisplayed.value = value`, т.к. внутри этого присвоения может еще происходить проверка данных и вызов подписчиков, а обращаемся как к обычному свойству.
А если писать `this.state.imageDisplayed.set(value)`, то понятно, что в этой функции может происходить что-то еще, помимо присвоения. То есть при использовании сеттеров есть скрытые сценарии, которые легко пропустить.

Но в целом не проблема, поправлю)

**Comment by Nelliza** [comment]
> А если писать `this.state.imageDisplayed.set(value)`, то понятно, что в этой функции может происходить что-то еще, помимо присвоения. То есть при использовании сеттеров есть скрытые сценарии, которые легко пропустить.

Круто, что возникают такие мысли о непрозрачности - действительно, аксессорами тоже стоит пользоваться аккуратно ) Но учитывая, что у тебя в коде ничего криминального не происходит:
> т.к. внутри этого присвоения может еще происходить проверка данных и вызов подписчиков

думаю, здесь аксессоры будут как нельзя кстати

**Comment by Nelliza** [comment]
Раз ты вынес названия css-классов в отдельный json, было бы круто добавить еще немного гибкости ) В pug-файлах предлагаю также инклудить эти json-объекты и ссылаться на их поля при присвоении классов, таким образом при переименовании классов в pug-файлы уже тоже не придется лезть. Только один нюанс - названия некоторых классов у тебя уже сразу с префиксом js-, тут проще убрать префикс из json-объектов и добавлять его в самих pug- и js-файлах при необходимости

**Comment by Nelliza** [comment]
Добавь плиз для приватных методов префикс `_` для наглядности (это требование есть в [стандартах](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#8.4))

**Comment by fmvasilenko** [comment]
> думаю, здесь аксессоры будут как нельзя кстати

Аксессоры добавил

**Comment by fmvasilenko** [comment]
Добавил json файлы с классами в pug
