### ISSUE TITLE
Приватные методы

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#28]
Добавь плиз для приватных методов префикс `_` для наглядности (это требование есть в [стандартах](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#8.4))

**Comment by fmvasilenko** [comment]
> Добавь плиз для приватных методов префикс `_` для наглядности (это требование есть в [стандартах](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#8.4))

Хорошо, добавлю)
Я ориентировался на стайлгайд от airbnb [23.4](https://github.com/airbnb/javascript#naming--leading-underscore).
Там указано, что лучше не использовать '_'.
Приватность методов реализована через замыкания в файлах с фасадами.
Снаружи компонентов доступно только их public API.

**Comment by fmvasilenko** [comment]
Добавил префиксы

**Comment by Nelliza** [comment]
> Хорошо, добавлю)
> Я ориентировался на стайлгайд от airbnb [23.4](https://github.com/airbnb/javascript#naming--leading-underscore).
> Там указано, что лучше не использовать '_'.
> Приватность методов реализована через замыкания в файлах с фасадами.
> Снаружи компонентов доступно только их public API.

Ага, все верно по airbnb, но тут наши стандарты переопределяют их стайлгайд:
> - [1.4](#1.4) Знать и использовать стайлгайд от AirBnB.
> ...
> Все, что перечислено в гайде принять к исполнению, если это не перекрыто нашими правилами ниже.

https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#1.4

**Comment by Nelliza** [comment]
Можешь плиз ссылаться на номер ишью в названиях коммитов? Так удобнее просматривать потом

**Comment by fmvasilenko** [comment]
> Можешь плиз ссылаться на номер ишью в названиях коммитов? Так удобнее просматривать потом

Да, просто в этот раз их было довольно много и я пропустил этот момент.
Вот ссылки на коммиты:
https://github.com/fmvasilenko/TOXIN/commit/01235be5c1f93a9937b63c5eb8fe6b89fc0f8d1d
https://github.com/fmvasilenko/TOXIN/commit/d9e4257fa48106ce5cdfe468e9a1241ed36fbc25
https://github.com/fmvasilenko/TOXIN/commit/34dcd8cd835e8420c3e96fb79e505595f4b896bf
https://github.com/fmvasilenko/TOXIN/commit/2214d5d71c7d44e93ddb66b413d9a14d6f329ad5
https://github.com/fmvasilenko/TOXIN/commit/3630f7b795bc123d2390cf681bbfa5bb88f97f40
https://github.com/fmvasilenko/TOXIN/commit/b75a504a75e763636ef79c7ad1d3e5ee8061405a
https://github.com/fmvasilenko/TOXIN/commit/1dc042a926eedbeca5e21b8065394e21a5f01843
https://github.com/fmvasilenko/TOXIN/commit/293fbdc1186afd97de38b5c2f63fddaaddd712d4
https://github.com/fmvasilenko/TOXIN/commit/0527100e184abb0b17c5040650d15e79d6e892ea
https://github.com/fmvasilenko/TOXIN/commit/668f77950288261461e4f31b5279299477571ed5
https://github.com/fmvasilenko/TOXIN/commit/f3bbe43a1f0740ba7b0bb9469c8812e76657c998
https://github.com/fmvasilenko/TOXIN/commit/63598310bbc06f5fccb4db5766d79bceed189624
https://github.com/fmvasilenko/TOXIN/commit/a79f034d0f97d66be2aada15572b8e00a7ed6aec
https://github.com/fmvasilenko/TOXIN/commit/ead58da883414fdcf4ed2dcbfce6eed90d3119aa
https://github.com/fmvasilenko/TOXIN/commit/a4791b4dc45f6011b88f20ef481763e6f48d2959
https://github.com/fmvasilenko/TOXIN/commit/370d1c288cfa9c012dea07d2dc0e9594d2321194
https://github.com/fmvasilenko/TOXIN/commit/ab0cee32df97f09fd80c867f622a7e7a60714753
