### ISSUE TITLE
Константы

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#30]
https://github.com/fmvasilenko/TOXIN/blob/25f7f5f90b1e5e2993c087821756e2da668b5ce6/src/common.blocks/calendar/CalendarLogic.js#L223
https://github.com/fmvasilenko/TOXIN/blob/25f7f5f90b1e5e2993c087821756e2da668b5ce6/src/common.blocks/calendar/CalendarLogic.js#L236

Подобные значения лучше выносить в константы и давать им осмысленные имена

**Comment by fmvasilenko** [comment]
Случайно сделал коммит без ссылки на ишью, так что вот ссылка на коммит:
https://github.com/fmvasilenko/TOXIN/commit/a69e73579c601079aa95654ed6da0b9a81088627

**Comment by Nelliza** [comment]
https://github.com/fmvasilenko/TOXIN/blob/a69e73579c601079aa95654ed6da0b9a81088627/src/common.blocks/calendar/CalendarLogic.js#L6
Это же неизменная величина, здесь напрашивается именно константа вместо поля класса
