### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by kate-fsd** [fmvasilenko/TOXIN#36]
![image](https://user-images.githubusercontent.com/66846004/102390497-85d01780-3fe5-11eb-8dff-21e61c361c3c.png)
![image](https://user-images.githubusercontent.com/66846004/102390551-96808d80-3fe5-11eb-94f0-9972c0a04800.png)

В макете кнопки с градиентом

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/102391287-8e751d80-3fe6-11eb-87cf-ed2542ce7420.png)
![image](https://user-images.githubusercontent.com/66846004/102391237-7dc4a780-3fe6-11eb-9f83-cad0c52fbb03.png)

Не совпадает размер штрифта, в макете 14. Нет серых подписей

**Comment by kate-fsd** [comment]
![new](https://user-images.githubusercontent.com/66846004/102391899-6803b200-3fe7-11eb-80fd-7f6de604f985.gif)

Галочки остаются

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/102393656-ba45d280-3fe9-11eb-97ea-e8e8321191c9.png)

При наведении должны появляться тени. Сверься еще с макетом по этой карточке, вижу что цвет не тот где отзывы, а люкс возможно не того шрифта

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/102394441-d0a05e00-3fea-11eb-8991-238774627e02.png)
![image](https://user-images.githubusercontent.com/66846004/102394479-dac25c80-3fea-11eb-98ba-996b4ebbf316.png)

Проверь тут шрифт пожалуйста. Верхнее твое, нижнее из макета

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/102394634-19581700-3feb-11eb-8f07-1cf30622dc52.png)
![image](https://user-images.githubusercontent.com/66846004/102394662-24ab4280-3feb-11eb-8d75-ee16d66235ee.png)

Градиент

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/102398359-3ba06380-3ff0-11eb-84a3-633335f11e23.png)

В верхнем инпуте шрифт не тот

**Comment by fmvasilenko** [comment]
> Не совпадает размер штрифта, в макете 14. Нет серых подписей

Добавил размер шрифта.
А серые надписи я специально не делал) Они же чисто технические, показывают состояния элементов. На проекте нигде  не используются.

**Comment by fmvasilenko** [comment]
> Градиент

А тут я не знаю что сделать. Я скопировал эти значки как SVG вместе с цветом. Попробовал только что еще раз, результат тот же самый(
Не вручную же цвета подбирать, чтоб совпало)

**Comment by kate-fsd** [comment]
> Не совпадает размер штрифта, в макете 14. Нет серых подписей

В дропдаунах тоже

**Comment by kate-fsd** [comment]
> При наведении должны появляться тени.

Не там) Посмотри в фигме на странице cards. Верхняя при наведении, нижняя без. Когда наводишь на картинке в карточке появляются тени и белая стрелка, убираешь мышь - они исчезают

**Comment by kate-fsd** [comment]
еще на этой карточке на "люкс" не тот шрифт

**Comment by kate-fsd** [comment]
> А тут я не знаю что сделать. Я скопировал эти значки как SVG вместе с цветом. Попробовал только что еще раз, результат тот же самый(
> Не вручную же цвета подбирать, чтоб совпало)

Вставила на странице cards. Проверь как ведет себя на разных страницах
![image](https://user-images.githubusercontent.com/66846004/103217974-f141af80-492a-11eb-8202-d927977a1eda.png)

**Comment by fmvasilenko** [comment]
Опять забыл проставить номер ишью)

**Comment by fmvasilenko** [comment]
> Вставила на странице cards. Проверь как ведет себя на разных страницах
> ![image](https://user-images.githubusercontent.com/66846004/103217974-f141af80-492a-11eb-8202-d927977a1eda.png)

А в чем тут проблема, я не очень понял)  
Градиент же отображается, просто немного не так, как в макете

**Comment by kate-fsd** [comment]
> А в чем тут проблема, я не очень понял)
> Градиент же отображается, просто немного не так, как в макете

Сделай так чтобы соответствовал макету. Ищи что именно влияет на неправильное отображение
