### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by kate-fsd** [fmvasilenko/TOXIN#38]
![image](https://user-images.githubusercontent.com/66846004/102397213-a2248200-3fee-11eb-9f31-8cad9a46fb62.png)

1. Лучше на такой ширине уже поставить кнопку для открытия меню, чтоб оно не разъезжалось
2. Нужно что то сделать с картинками, так выглядит плохо
3. Задай максимальную ширину для формы

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/102397612-26770500-3fef-11eb-98ad-300361cff712.png)

2 отзыва слишком близко

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/102397999-c03eb200-3fef-11eb-8ac9-efd1addb463a.png)

Нужно добавить отступ от края

**Comment by fmvasilenko** [comment]
Забыл проставить номер ишью в коммитах, так что вот ссылки:  
https://github.com/fmvasilenko/TOXIN/commit/49a11f338af3cc46b594bc68d554758546d42963
https://github.com/fmvasilenko/TOXIN/commit/6dfb508050e9e056b8554001a03e59161fc5a6bc
https://github.com/fmvasilenko/TOXIN/commit/33899f908e9623a33e82c865c1ddcf99ea2ce61f
https://github.com/fmvasilenko/TOXIN/commit/f64779f90db3854e9d63c1fe4b747221924e00ab
https://github.com/fmvasilenko/TOXIN/commit/4495896bd0ca64976824f8391fa00b25d4e96487
