### ISSUE TITLE
Кнопки

### ISSUE THREAD

**Issue by kate-fsd** [fmvasilenko/TOXIN#39]
При использовании кнопки, каждый раз ты вынужден задавать ее обертке высоту. Сделай высоту сразу на кнопке, чтобы компонент сам по себе выглядел хорошо 

![image](https://user-images.githubusercontent.com/66846004/102869592-e2e82500-444c-11eb-9b7a-de0a9fd45a37.png)

**Comment by kate-fsd** [comment]
Поправь padding right
![image](https://user-images.githubusercontent.com/66846004/102871411-73c00000-444f-11eb-9aa5-55ae06702c92.png)

**Comment by fmvasilenko** [comment]
> При использовании кнопки, каждый раз ты вынужден задавать ее обертке высоту. Сделай высоту сразу на кнопке, чтобы компонент сам по себе выглядел хорошо

Тут я специально так делал, поскольку в макете есть кнопки разной высоты (например в формах и в хедере). Соответственно мы заранее не знаем какая высота будет подходящей, поэтому размеры задаются контейнером.  
Изначально у меня была задана высота в 44px, как в form-elements.  
Если критично - могу поставить `min-width: 34px` (как в хедере), но мне кажется, это не совсем корректно)

**Comment by kate-fsd** [comment]
> Тут я специально так делал, поскольку в макете есть кнопки разной высоты (например в формах и в хедере). Соответственно мы заранее не знаем какая высота будет подходящей, поэтому размеры задаются контейнером.
> Изначально у меня была задана высота в 44px, как в form-elements.
> Если критично - могу поставить `min-width: 34px` (как в хедере), но мне кажется, это не совсем корректно)

Для этого лучше использовать модификаторы. У тебя есть два состояния кнопки - высокая и поменьше, и лучше не давать возможности при ее использовании самостоятельно задавать высоту. Во первых, есть шанс что гипотетический человек использующий этот компонент поленится смотреть высоту кнопки на других страницах и задаст ее на глаз. Второе - это неудобно и неправильно, что приходится искать высоту самому, а не передавать понятный параметр высокая/низкая

**Comment by kate-fsd** [comment]
Страница login
![image](https://user-images.githubusercontent.com/66846004/104439821-9e126280-55a2-11eb-94d3-586e2a6e69f6.png)

**Comment by fmvasilenko** [comment]
> Страница login

Я посмотрел в чем проблема:  
У кнопки размер равен 100px, padding - по 20px и контент 61,7px. Он не влезает)  
  
Соответственно, можно:  
1. Поменять padding, но тогда изменятся в размерах и другие кнопки, в которых ширина определяется контентом, например в хедере.
2. Немного отойти от макета и поменять в этом конкретном случае ширину со 100px на 102px. PixelPerfect будет уже не идеальный, но, в отличие от первого варианта, несовпадение будет только у одной кнопки, а не по всему проекту.
3. Сделать отдельный класс для кнопки: без фона и без паддингов, специально для этой ситуации. Из минусов - это дополнительное усложнение компонента.  
  
Возможно, имеет место "ошибка" дизайнера, т.к. по проекту паддинги везде идут 20px, а здесь левый - 18px, а правый - 19px. Предположу, что дизайнер мог поместить туда текст "на глаз" и не проверить совпадение отступов.  
  
Соответственно, вопрос: как лучше решить эту проблему?)  
Пока что, я поменял ширину этой конкретной кнопки на 102px, чтобы проблема не бросалась в глаза)

**Comment by kate-fsd** [comment]
> Соответственно, вопрос: как лучше решить эту проблему?)

Можно padding поставить меньший, 18px (или еще меньше) и min-width: 100px.

Но пусть остается как есть сейчас, два пикселя - не страшно)
