### ISSUE TITLE
Pixel Perfect

### ISSUE THREAD

**Issue by kate-fsd** [fmvasilenko/TOXIN#40]
На странице вход
![image](https://user-images.githubusercontent.com/66846004/104461575-95c92000-55c0-11eb-8056-6e9c62e1433a.png)

**Comment by kate-fsd** [comment]
Пончик отличается - градиенты, жирность текста
![image](https://user-images.githubusercontent.com/66846004/104462179-48997e00-55c1-11eb-9102-608831169f44.png)
![image](https://user-images.githubusercontent.com/66846004/104462217-53eca980-55c1-11eb-9888-e11ac444cfc9.png)

**Comment by kate-fsd** [comment]
Отцентрируй сердечко по вертикали
![image](https://user-images.githubusercontent.com/66846004/104462347-85657500-55c1-11eb-827c-7c03cb769698.png)

**Comment by kate-fsd** [comment]
Здесь символ рубля добавь пожалуйста
![image](https://user-images.githubusercontent.com/66846004/104462819-13d9f680-55c2-11eb-8d69-d7f22056295b.png)

**Comment by fmvasilenko** [comment]
> На странице вход

![image](https://user-images.githubusercontent.com/62238648/104901653-b9101880-598e-11eb-9b1a-37d491f0a49a.png)

У меня все совпадает) И такой ишьюс уже [был](https://github.com/fmvasilenko/TOXIN/issues/22), и на тот момент решили ничего не менять)  
Сейчас как лучше поступить?)  
Я могу, например, править по твоему скриншоту, но тогда у меня не будет PerfectPixel совпадать
