### ISSUE TITLE
Автоимпорт

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#5]
Настрой пожалуйста глобально в проекте автоматический импорт стилевых и скриптовых файлов во избежание вот такой простыни из импортов:
https://github.com/fmvasilenko/TOXIN/blob/4bcd0b65ddea35306166276d20e7fc3698966b5c/src/scss/main.scss#L122-L164
Автоимпорт также избавит тебя от необходимости вручную править пути при изменении / добавлении файлов

**Comment by fmvasilenko** [comment]
@Nelliza, здесь есть одна проблема:
В проекте используется ряд переменных, расположенных в `src/scss/utils/vars.scss`. 
Файл подключается в `src/scss/main.scss`. 
```
// main.scss

@import 'utils/vars.scss';
...
```
Если настраивать автоматический импорт в `index.js` через
```js
// index.js

import './scss/main.scss';

const styles = require.context('./common.blocks/', true, /\.scss/);
styles.keys().forEach(styles);
```
то возникает ошибка с областью видимости.

То есть, поскольку файлы подключаются отдельно в `index.js`, они не видят `vars.scss` в `main.scss`.  
Я пока вижу 3 варианта решения:
1. Убрать изо всех scss файлов переменные и заменить их просто на значения
2. Во все scss файлы добавить импорт `vars.scss`
3. Оставить все как есть

Вопрос в том, какой из вариантов наилучший? Или может есть еще какие-то?

**Comment by Nelliza** [comment]
@fmvasilenko думаю, самым оптимальным здесь является второй вариант. Во всяком случае, я при выполнении заданий воспользовалась именно им )
