### ISSUE TITLE
Именование директорий и файлов

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#6]
![1](https://user-images.githubusercontent.com/19621113/89206103-6ea60580-d5c1-11ea-9572-1bf29160e870.png)
Именование файлов и папок проекта должно быть единообразным и выполнено в `lower-case-hyphenated` стиле (за исключением скриптовых файлов, для них стайлгайд от airbnb предлагает [отдельные правила именования](https://github.com/airbnb/javascript#naming-conventions))

**Comment by Nelliza** [comment]
_searchroom_ - в имени этой директории тоже не хватает дефиса между словами

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/90051459-6431ed00-dce0-11ea-8041-c5931f5e81e8.png)
Изображения тоже следует именовать по такому же принципу, и здесь еще нужно подумать над более осмысленными именами для них

**Comment by Nelliza** [comment]
Еще в папке _layout_ посмотри пожалуйста

**Comment by Nelliza** [comment]
И еще раз внимательно пройдись плиз по проекту - где-то встречала `snake_case` в именовании, тоже нужно поправить

**Comment by fmvasilenko** [comment]
> Для именования js-файлов с классами используем `PascalCase`

Думаю, здесь проблема была та же, что и в #8.
Названия я все менял, но они не коммитились. Сейчас должно быть все в порядке
