### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#7]
![1](https://user-images.githubusercontent.com/19621113/89207310-343d6800-d5c3-11ea-8325-42d2f96b6535.png)
Согласно [БЭМ-методологии](https://ru.bem.info/methodology/key-concepts/), элемент не может содержать внутри себя блок, к которому он относится

**Comment by Nelliza** [comment]
https://github.com/fmvasilenko/TOXIN/blob/4bcd0b65ddea35306166276d20e7fc3698966b5c/src/common.blocks/bullet/bullet.pug#L6
Миксин должен возвращать одноименный блок со всеми вложенными элементами, а не просто элемент блока

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/89207931-3227d900-d5c4-11ea-84f0-0149aa0f8b9b.png)
Не следует дробить стилевые файлы по элементам, содержащим по паре строчек кода. Это усложняет структуру, достаточно разделять файлы по блокам

**Comment by Nelliza** [comment]
https://github.com/fmvasilenko/TOXIN/blob/12d4d85f27e38c5e183ab604c19aeed3b7588ef3/src/common.blocks/date-dropdown/date-dropdown.pug#L13
https://github.com/fmvasilenko/TOXIN/blob/12d4d85f27e38c5e183ab604c19aeed3b7588ef3/src/common.blocks/date-dropdown/date-dropdown.pug#L18
А почему здесь разные имена у основного класса и класса с префиксом?

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/90054390-7ada4300-dce4-11ea-87bd-1a12b118b722.png)
Здесь напрашивается выделение этого элемента в отдельный компонент

**Comment by fmvasilenko** [comment]
> https://github.com/fmvasilenko/TOXIN/blob/12d4d85f27e38c5e183ab604c19aeed3b7588ef3/src/common.blocks/date-dropdown/date-dropdown.pug#L13
> 
> 
> https://github.com/fmvasilenko/TOXIN/blob/12d4d85f27e38c5e183ab604c19aeed3b7588ef3/src/common.blocks/date-dropdown/date-dropdown.pug#L18
> 
> 
> А почему здесь разные имена у основного класса и класса с префиксом?

Потому что с точки зрения стилей нужен был всего один класс, а с точки зрения js - это два разных поля и для их поиска используются два отдельных класса.
Я могу переделать, если нужно, просто мне казалось, что классы с префиксом и без могут отличаться, так как используются для разных целей? Собственно, классы с префиксами и нужны для того, чтобы отделить логику от стилей?

**Comment by Nelliza** [comment]
> Я могу переделать, если нужно, просто мне казалось, что классы с префиксом и без могут отличаться, так как используются для разных целей? Собственно, классы с префиксами и нужны для того, чтобы отделить логику от стилей?

Нет, префикс должен дублировать имя класса, об этом прямо указано в [стандартах](https://github.com/fullstack-development/front-end-best-practices/blob/ab34d8dda4b306dfe44afee9b96bef4890f9b166/JS/README.md):
> Например, есть кнопка, по клику открывающая попап - нам надо **продублировать** ее класс и добавить туда этот префикс:
>  ```html
>  <div class="open-popup-button js-open-popup-button"></div>
>  ```

**Comment by Nelliza** [comment]
> Потому что с точки зрения стилей нужен был всего один класс, а с точки зрения js - это два разных поля и для их поиска используются два отдельных класса.

В JS существуют альтернативные способы поиска элементов, помимо поиска по классу, здесь целесообразно подумать в этом направлении )

**Comment by fmvasilenko** [comment]
> > Потому что с точки зрения стилей нужен был всего один класс, а с точки зрения js - это два разных поля и для их поиска используются два отдельных класса.
> 
> В JS существуют альтернативные способы поиска элементов, помимо поиска по классу, здесь целесообразно подумать в этом направлении )

Вот тут, если честно, не понял. Можно искать элемент по разным параметрам (id, тэг, класс и т.д.), но поиск по классу - наилучший вариант, насколько я понимаю. 
Можно найти оба поля по одному классу, а дальше обратиться к ним как к элементам массива: 
```js
const dateDropdownInput = container.querySelectorAll('js-date-dropdown__input');

const arrivalDateInput = dateDropdownInput[0];
const leavingDateInput = dateDropdownInput[1];
```
Но мне непонятно преимущество такого метода.  

Самым оптимальным вариантом мне видится:
```pug
input.date-dropdown__arrival-date.js-date-dropdown__arrival-date
input.date-dropdown__leaving-date.js-date-dropdown__leaving-date
```
И в стилях писать:
```css
.date-dropdown__arrival-date,
.date-dropdown__leaving-date {
  ...
}
```

**Comment by Nelliza** [comment]
А если бы ты работал не с элементами, а с блоками, как бы ты использовал групповые селекторы в данном случае? Я считаю, это неверно - разделять по сути единую сущность только для получения доступа в скрипте при том, что у тебя под рукой есть все необходимое для нормального поиска, даже не нужно ничего изобретать. Причем поиск по классу это никак не отменяет, нужно просто добавить дополнительный фильтр по атрибуту (к примеру, `name`)

**Comment by Nelliza** [comment]
> А что тогда делать в `common.blocks/dropdown`? Там такая же ситуация, но нету атрибута name.

Там явно модификаторы напрашиваются, т.к. элементы схожи, но не идентичны, в т.ч. стилистически

**Comment by fmvasilenko** [comment]
> > А что тогда делать в `common.blocks/dropdown`? Там такая же ситуация, но нету атрибута name.
> 
> Там явно модификаторы напрашиваются, т.к. элементы схожи, но не идентичны, в т.ч. стилистически

Различия в стилях у меня задаются в миксинах, через конфиг кнопки. То есть если я здесь добавлю модификаторы, то для них не будет стилей. Это нормально, добавить класс элементу, но никак не описать его в css?

**Comment by Nelliza** [comment]
> Различия в стилях у меня задаются в миксинах, через конфиг кнопки. То есть если я здесь добавлю модификаторы, то для них не будет стилей. Это нормально, добавить класс элементу, но никак не описать его в css?

Нет, не нормально ) Имеешь в виду, что модификаторы добавляются для вложенных элементов, а эти получается родительские, и они ничем не отличаются стилистически? Если да, то в этом случае можно использовать кастомный дата-атрибут. Кстати, по вопросу дата-атрибутов также открыла ишью #11

**Comment by Nelliza** [comment]
https://github.com/fmvasilenko/TOXIN/blob/7a392616775117508b01f267c76a20be2cd6d67b/src/common.blocks/benefit/benefit.scss#L8
Не очень удачное имя для модификатора, здесь напрашивается либо модификатор типа "ключ-значение", либо, если других рамок не предвидится и это булев модификатор, следует подобрать более подходящее имя (по аналогии с булевыми переменными, у нас [в стандартах](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#variable-naming--boolean) есть инфа по вопросу). Пройдись плиз по всему проекту на предмет подобных исправлений

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/92310873-e5686100-efba-11ea-83d9-169429ec2d45.png)
Странный класс у кнопки входа )

**Comment by Nelliza** [comment]
https://github.com/fmvasilenko/TOXIN/blob/9220eb80bbb223401960e0f5654f86ccc98e4817/src/pages/cards/cards.scss#L12
`wrapper` - не слишком подходящее имя для дочернего элемента, такое имя скорее годится для родительского DOM-элемента, оборачивающего дочерний. Видела еще в проекте подобное именование, посмотри и поправь пожалуйста везде
