### ISSUE TITLE
Не собирается проект

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#8]
Сейчас ошибки сыплются при сборке
![1](https://user-images.githubusercontent.com/19621113/90050939-955ded80-dcdf-11ea-8a20-b8a0f72a0405.png)

**Comment by fmvasilenko** [comment]
Мне кажется, что проблема здесь была в том, что имена шрифтов в main.scss не совпадали с фактическими. 
В частности, в одном из коммитов я во всех названиях шрифтов поменял прописные буквы на строчные, а git, видимо,  решил, что ничего не поменялось и не добавил изменения в коммит.

Это пока единственная возможная причина, которую я нашел. 
У меня все собирается, поэтому жду обратной связи.

**Comment by Nelliza** [comment]
Да, файловые системы винды являются регистронезависимыми, отсюда и проблемы. Другой вопрос, что проект все равно не собирается по инструкции, приведенной в [README.md](https://github.com/fmvasilenko/TOXIN#1-initialization)

**Comment by Nelliza** [comment]
Теперь другие ошибки
![1](https://user-images.githubusercontent.com/19621113/90822285-de93ea00-e33c-11ea-9c48-e2ba9f3a64e0.png)

**Comment by Nelliza** [comment]
Тут дело не в `run` - я и раньше с `run` запускала, проблема не в этом (см. скрин выше)

**Comment by fmvasilenko** [comment]
> Тут дело не в `run` - я и раньше с `run` запускала, проблема не в этом (см. скрин выше)

Он пишет, что `Can't resolve '@blocks/calendar/Calendar` in `.../common.blocks/date-dropdown`
У меня такие штуки выдает, если в `node_modules` нет ссылок `@blocks, @backend, @frontend`. Чтобы они проставились, я добавил команду `postinstall`. Ее до этого не было. У меня ссылки генерировались автоматически. 
Я думаю, что дело может быть в этом?

**Comment by Nelliza** [comment]
В том-то и дело, что они есть:
![1](https://user-images.githubusercontent.com/19621113/91348934-31fab200-e7ed-11ea-8acf-6843c731bff6.png)

**Comment by Nelliza** [comment]
> Чтобы они проставились, я добавил команду `postinstall`

Я добавляла эту команду и раньше, конечно readme в любом случае нужно было поправить, но к сожалению, дело не в этом

**Comment by fmvasilenko** [comment]
Хмм.. Что-то ничего в голову не приходит(
Там не указаны расширения файлов, но, по идее, webpack и так их должен находить.
Может тогда правильнее вообще избавиться от aliases и переписать все в относительных путях?

**Comment by fmvasilenko** [comment]
Завтра посмотрю еще что к чему

**Comment by fmvasilenko** [comment]
Из того, что мне удалось найти:
Если сделать git clone, то у меня все собирается, но линтер говорит, о том, что пути не верны.
Оказалось, после переименования js файлов, те, у которых поменялся только регистр в названии - не коммитились (как и в прошлый раз).
В общем, я перекоммитил всю папку src с правильными именами файлов, теперь линтер не ругается.
Надеюсь, причина была в этом)

**Comment by Nelliza** [comment]
Ура, наконец собрался проект )

**Comment by Nelliza** [comment]
Только теперь нужно подправить readme - команда `postinstall` на этапе установки не нужна же, она ведь возвращает ранее удаленные каталоги (`@plugins`, `@frontend` и `@blocks`)

**Comment by Nelliza** [comment]
И еще один момент: сейчас при запуске проекта ничего не отображается (пустая страница) - это не комильфо, следует сделать так, чтобы при запуске отображалась главная страница
