### ISSUE TITLE
Изображения

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/TOXIN#9]
Изображения, относящиеся к конкретным блокам / страницам, следует разнести по директориям этих блоков / страниц. А в папке _img_ допустимо оставить какие-то общие изображения

**Comment by Nelliza** [comment]
Также следует оптимизировать изображения:
> 4. **Прогонять картинки через [kraken.io](https://kraken.io/) или использовать свои CLI-утилиты для этого**;

**Comment by fmvasilenko** [comment]
> Изображения, относящиеся к конкретным блокам, следует разнести по директориям этих блоков. А в папке _img_ допустимо оставить какие-то общие изображения

Здесь вопрос в том, что все изображения используются или могут использоваться в разных блоках:
- изображения номеров - в `common.blocks/suite` и `pages/room-details`
- фото пользователей - в `common.blocks/feedback`, но потенциально могут использоваться и в других местах, например на личной странице пользователя
- фоновые изображения повторяются на разных страницах, например `background2.png` используется в `login` и `registration`

На сколько я понимаю, изображения стоит переносить в папки с блокам только если они относятся к конкретному блоку и используются только в нем (фоновое изображение блока, например)?
А в остальных случаях изображения хранятся в общей директории и пути к ним подгружаются из БД

**Comment by Nelliza** [comment]
> Здесь вопрос в том, что все изображения используются или могут использоваться в разных блоках

Есть изображения, не являющиеся общими, используемые только на конкретных страницах, но в целом да, выглядит логично - потенциально эти фоновые изображения могут меняться на другие подобные, поэтому соглашусь с тобой

**Comment by Nelliza** [comment]
> Здесь вопрос в том, что все изображения используются или могут использоваться в разных блоках

Есть изображения, не являющиеся общими, используемые только на конкретных страницах, но в целом да, выглядит логично - потенциально эти фоновые изображения могут меняться на другие подобные. Поэтому соглашусь с тобой, тут наверное достаточно было разбить на смысловые блоки, что ты и сделал

**Comment by Nelliza** [comment]
А что по поводу оптимизации?

**Comment by fmvasilenko** [comment]
> А что по поводу оптимизации?

Еще не успел, завтра утром загружу. Читал про разные форматы изображений и варианты сжатия и оптимизации.

**Comment by Nelliza** [comment]
> Еще не успел, завтра утром загружу. Читал про разные форматы изображений и варианты сжатия и оптимизации.

Ок, подумала, пропустил )

**Comment by Nelliza** [comment]
Я имела в виду сжатие изображений, к примеру, я использовала для этого `image-webpack-loader`
